# https://solace.com/products/event-broker/software/getting-started/

services:
  # 1) Hyperledger Fabric
  ca.org1.example.com:
    image: hyperledger/fabric-ca:1.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=false
    ports:
      - "7054:7054"
    volumes:
      - ./fabric/ca/org1/:/etc/hyperledger/fabric-ca-server
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'

  orderer.example.com:
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    ports:
      - "7050:7050"
    volumes:
      - ./fabric:/etc/hyperledger/configtx
      - ./fabric/msp/orderer-org1:/etc/hyperledger/msp/orderer/msp

  peer0.org1.example.com:
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/msp
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - "7051:7051"
      - "7053:7053"
    volumes:
      - ./fabric/msp/peer0-org1:/etc/hyperledger/msp/peer/msp
      - ./fabric:/etc/hyperledger/configtx
      - /var/run/:/host/var/run/

  # 2) Graph DB
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword
    volumes:
      - ./graph-db/docker/data:/data

  # 3) OpenLDAP
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION="ExampleCorp"
      - LDAP_DOMAIN="example.com"
      - LDAP_ADMIN_PASSWORD="adminpassword"
    volumes:
      - ./openldap/docker/data:/var/lib/ldap
      - ./openldap/docker/config:/etc/ldap/slapd.d

  # 4) Solace PubSub Standard
  pub-sub:
    image: solace/solace-pubsub-standard:latest
    container_name: solace-standard
    ports:
      # configuring the message
      - '8081:8080'
      # APIs to connect to the message broker
      - '55554:55555'
      - '8008:8008'
      - '1883:1883'
      - '8000:8000'
      - '5672:5672'
      - '9000:9000'
      - '2222:2222'
    shm_size: '2g'
    environment:
      - username_admin_globalaccesslevel=admin
      - username_admin_password=admin
      - SOLACE_MGMT_USERNAME=admin
      - SOLACE_MGMT_PASSWORD=admin
      - SOLACE_ENABLE_CLI=true

networks:
  default:
    name: project-network